### ISSUE TITLE
Gimkit

### ISSUE THREAD

**Issue by FloppyT** [UndercoverGoose/quizlet#2]
This doesn't work, JSON is not reliable.

P.S
The Terms of Service of Gimkit are against hacking and cheating.

**Comment by UndercoverGoose** [comment]
Now the JSON is no longer usable, I have resorted to the backup method of trial and error.

All you have to do is get the question wrong (You will be able to answer correctly soon), and view the correct answer. The question and answer will be logged, and Highlight Answer etc. will all work with that specific question, once you've gone through every question, it will work just like it did before.

Plus, I am not responsible for anything done with these scripts, I just make them in my free time.

**Comment by FloppyT** [comment]
The JSON is usable, but it will be fixed soon. Good luck on you script

Plus, I am not using these scripts, I'm just looking at them.

**Comment by FloppyT** [comment]
Also their detector is server side, so don't bother trying to disable it. The only way the "script" will work is if it is slower and not as strong.

**Comment by FloppyT** [comment]
There are many solutions to your problem, without having to using a "learning bot". I can not tell you these solutions, but they are there, search for them

**Comment by FloppyT** [comment]
Congrats on fixing this, the `games/fetch` method is pretty reliable, but still their detector is unavoidable and will force you to slow this down.

**Comment by FloppyT** [comment]
These "kit Ids" are UUIDs that are almost randomly selected. They do not contain kit-identifying data ( and if they do, it would be very little. ) These UUIDs are random selected combined with time, hence if you create two kits in the same second - they both have a very very similar UUID. 
Hope this helps your investigation

**Comment by FloppyT** [comment]
@UndercoverGoose, since you and others seem to be stumped on how to get the gameID, I've made this simple script that should help you in your code. Use peacefully, enjoy 

```js

const state = {
    token: Math.random() ** 20,
    gameID: null
};

// Redefine game id on every single object in all of gimkit's code

Object.defineProperty({}.__proto__, "game", {
    get() {return this["gameID" + state.token]},

    set(val) {
        // When gimkit attempts to set the game id, retrieve it.
        console.log('GAMEID RETRIEVED ' + val);
        this["gameID" + state.token] = state.gameID = val;
        return val
    }
});
// Enjoy
```
