### ISSUE TITLE
Compile error with gimkit Javascript. 

### ISSUE THREAD

**Issue by slapsruler12** [UndercoverGoose/quizlet#5]
Line 9
Char 7
Expected ";"

**Comment by UndercoverGoose** [comment]
I need more information. How are you running the script? Can you paste in the section of the script that is causing the error?

**Comment by j0e133** [comment]
let qs = [],
      as = [];
  let list = [];
  for(let x=0;x<JSON[Object.keys(JSON)[0]].length;x++) {
    list.push(parseInt(JSON[Object.keys(JSON)[0]][x]["_id"].slice(19,99),16))
  }

**Comment by j0e133** [comment]
"cannot read property length of undefined"
